# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('direccion', models.CharField(max_length=180)),
                ('visitas', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('votos', models.IntegerField(default=0)),
                ('nombrebar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Bares')),
            ],
        ),
    ]
